#!/bin/env bash

pushd $DOTFILES > /dev/null

if [ `command -v fd` ]; then
  CMD="fd --type f --hidden --follow --exclude .git -X ls -tu"
else
  CMD="find . -type f -not -path './node_modules*' -not -path '*.git*'"
fi

if [ -n "$TMUX" ]; then
  [[ `command -v lvim` ]] && EDITOR=lvim
  CHOSEN=`$CMD | fzf-tmux -p`
else 
  CHOSEN=`$CMD | fzf`
fi
RET=$?
popd > /dev/null
if [ $RET = 0 ]; then
  touch $DOTFILES/$CHOSEN
  $EDITOR "$DOTFILES/$CHOSEN"
fi

