#!/bin/env bash

if [ -z "$1" ]; then
  echo "usage: shebang <interpreter>"
  exit;
fi

INTERPRETER="$1"

if [ ! `command -v $1` ]; then
  echo "Interpreter not supported: $1"
  exit
fi

# read -p "Enter filename: " FILENAME

# if [ -e "$FILENAME" ]; then
#   echo "$FILENAME already exists"
#   exit
# fi

echo -e '#!/bin/env' "$INTERPRETER" | $EDITOR -c "filet detect"




