#!/bin/env bash

# PLAYLIST="https://www.youtube.com/watch?v=nMfPqeZjc2c"
PLAYLIST="https://www.youtube.com/watch?v=YPWG-GhyrZY"

notify-send "Playing Whitenoise.."

mpv \
  --x11-name=lofi \
  --shuffle \
  --force-window \
  --script-opts=osc-visibility=always \
  --ytdl-format="[height <=? 480][vbr < 800]+bestaudio" \
  "$PLAYLIST"
