#!/bin/env bash

# Find nearest TODO file with name of $TODO_NAME
set -eo pipefail
TODO_NAME="TODO.md"
PWD=${1:-"$PWD"}

IFS=$'\n'
FIND=( $(fd --exact-depth 1 --no-ignore --type file "$TODO_NAME" "$PWD") )

while [[ -z "$FIND" ]]; do
  [[ $PWD = '/' ]] || [[ $PWD = $HOME ]] && echo "$TODO_NAME is not found" && exit

  cd ..
  FIND=( $(fd --exact-depth 1 "$TODO_NAME" "$PWD") )
done

# echo $FIND

for each in "${FIND[@]}"; do
  echo "$each"
done
