#!/bin/env bash

source bash_util_fn

# brotab list | sed -r 's|([^\t]+)\t([^\t]+)\t([^\t]+)|\1\t\2|' | _cap

# brotab list | rofi -dmenu | _cap
brotab list \
| sed -r 's#([^\t]+)\t([^\t]+)\t([^\t]+)#\1\t\2#' \
| rofi -dmenu -async-pre-read 0 -p Tabs \
| _out_cap

tab_id="$(echo "$(_out_get)" | awk -F' ' '{print $1}')"
tab_title="$(echo "$(_out_get)" | awk -F' ' '{print $2}')"

_out_empty && exit 0

brotab activate "$tab_id"

WID=$(xdotool search --name "$tab_title" | tail -1)
xdotool windowactivate --sync "$WID"
