#!/bin/env bash

kwriteconfig5 --file kwinrc --group Plugins --key krohnkiteEnabled true
qdbus org.kde.KWin /KWin reconfigure

sleep 0.5

kwriteconfig5 --file kwinrc --group Plugins --key krohnkiteEnabled false
qdbus org.kde.KWin /KWin reconfigure

