#!/bin/env bash

export NVIM_CONFIG_HOME="$HOME/.config/vscode-neovim"
export XDG_CONFIG_HOME="$NVIM_CONFIG_HOME"
export XDG_DATA_HOME="$NVIM_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$NVIM_CONFIG_HOME/cache"
export XDG_STATE_HOME="$NVIM_CONFIG_HOME/local/state"

nvim "$@"
