#!/usr/bin/env bash
set -e

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git submodule update --init --recursive

# ------------------------------------------------------------------------------------------------ #
# Utility functions

# print line banner
printLineBanner() {
  printf '\e[1;34m%0.s#\e[0m' $(seq 1 $(stty size | awk '{print $2}'))
}

# ------------------------------------------------------------------------------------------------ #
# Verify dotbot profile exists
# Checks if the file exists in meta/profiles/ folder

exitIfProfileNotFound=false    # used as a flag to exit IF a profile is NOT found
for profile in ${@}; do
  profileFilepath="${BASE_DIR}/${META_DIR}/${PROFILES_DIR}/${profile}"

  if [[ ! -e $profileFilepath ]]; then
    echo -e "Dotbot profile \\033[1;31m$profileFilepath \\033[0mNOT found"

    exitIfProfileNotFound=true
  fi
done

if [[ $exitIfProfileNotFound == true ]]; then
  echo -e "\nexiting"
  exit 1
fi

# cleanup variables
unset exitIfProfileNotFound

# ------------------------------------------------------------------------------------------------ #
# Running profile

for profile in ${@}; do
    # extract dotbot configs to run
    while IFS= read -r config; do
        CONFIGS+=" ${config}"

    # read lines that DON'T start with #
    done < <(grep -v '^#' "${META_DIR}/${PROFILES_DIR}/$profile")

    # print line banner multiple times
    for i in `seq 2`; do printLineBanner; done
    echo -e "\nRunning profile \e[1;34m$profile\e[0m\n"

    # run profile configs
    source ./install-standalone ${CONFIGS}

    # cleanup variables
    unset CONFIGS
done

cd "${BASE_DIR}"

echo "Restart your terminal..."

