#!/usr/bin/env bash

set -e

usage(){
  echo "Usage: $0 [type] [target]"
  echo
  echo "type: type of installation to perform"
  echo "  'standalone': install standalone package (single package, e.g. nvim)"
  echo "  'profile': install profile (collection of packages, e.g. dev)"
  echo
  echo "target: path to install package or profile"
  echo
  echo "Examples:"
  echo "  $0 standalone nvim"
  echo "  $0 profile dev"
  exit 1
}

if [ $# -ne 2 ]; then
  usage
fi

if [ "$1" != "standalone" ] && [ "$1" != "profile" ]; then
  usage
fi
