# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# # Inserts a blank line between shell prompts
# # add_newline = true
# scan_timeout = 10
# command_timeout = 100
#
# [os]
# disabled = true
#
# [cmd_duration]
# min_time = 1
# format = '[$duration]($style) '
# # show_notifications = true
# # min_time_to_notify = 1000
#
# [docker_context]
# disabled = true

add_newline = false     # Inserts newline between shell prompts
scan_timeout = 10       # Timeout for scanning files
command_timeout = 500   # Timeout for starship commands (modules, etc)
format = """
$all\
$fill\
$kubernetes\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character
"""

[fill]
symbol = ' '
style = 'bold green'

[cmd_duration]
min_time = 1
format = '[$duration]($style) '
# show_notifications = true
# min_time_to_notify = 1000

[gcloud]
disabled = true
symbol = "󱇶 "
format = '[$symbol$active]($style) '

[golang]
symbol = " "
disabled = true

[docker_context]
disabled = true

[kubernetes]
format = '[$context( \($namespace\)) $symbol]($style)'
symbol = '\[k8s\]'
disabled = true
detect_env_vars = ['STARSHIP_KUBE_ENABLED']


[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>[\\w-]+prd[\\w-]*)"
context_alias = "gke-$cluster"
symbol = '\[k8s PROD\]'
style = "bold red"

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
context_alias = "gke-$cluster"
