git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  log:
    showGraph: always
    showWholeGraph: false

customCommands:
  - key: "G"
    command: "glab mr view {{.SelectedLocalBranch.UpstreamBranch}} | cat"
    context: "localBranches"
    description: "Go to MR in gitlab"
    loadingText: Opening Gitlab MR
    showOutput: True
    prompts:
      - type: confirm
        title: "glab"
        body: "Open GitLab MR using glab?"
  - key: '<c-f>'
    command: "git difftool -y {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
    context: 'commitFiles'
    description: 'Compare (difftool) with local copy'

gui:
  showIcons: true
  nerdFontsVersion: "3"

# os:
#   edit: "nvim --server $NVIM --remote-tab {{filename}}"
