#!/bin/env zsh

SESSION="PROJECT"
ROOT="~/Codes/IEO-2023"

# if ! $(tmux has -t "$SESSION" 2> /dev/null); then
#   tmux new -s "$SESSION" -d
# fi

tmux kill-session -t "$SESSION"
tmux new -s "$SESSION" -d

# tmux new-window -t "$SESSION" -c "$ROOT" "pwd; bash"

# tmux new-window -Sdt "$SESSION" \
#   -n "Client" \
#   -c "$ROOT/Client" \
#   ""


# tmux new-window -Sdt "$SESSION" \
#   -n "Keystone" \
#   -c "$ROOT/Keystone" \
#   sh
