#!/bin/env bash

# Start a tmux project with smug

# Usage:
#   work
#   work <project>
#   work stop

SESSION_TMP="/tmp/work"

if ! tmux has; then
	echo "Starting new tmux server.."
	tmux new-session -Ads 1
fi

# parse arguments using case
case "$1" in
"stop")
	# switch to attached client
	T="$(tmux ls | grep -v -m1 attached)"

	if [[ -n "$T" ]]; then
		tmux switchc -t $(cut -d ':' -f1 <<< "$T")
	else
		tmux new -d \; switch-client -n
	fi

	# stop the current project
	if [ -f "$SESSION_TMP" ]; then
		PROJECT=$(cat $SESSION_TMP)
		smug stop $PROJECT
		rm $SESSION_TMP
	else
		echo "No project is running"
	fi

	;;
"")
	# fuzzy find available projects
  SELECTED=$(smug list | fzf-tmux -p)
  echo "$SELECTED" > "$SESSION_TMP"

  [[ -n "$SELECTED" ]] && smug start $SELECTED -a
	;;
*)
	# project name

  if $(smug list | grep -m1 -qx "$1"); then
		echo "$1" > "$SESSION_TMP"
    smug start "$1" -a
  else
    echo "Project $1 not found"
  fi

	;;
esac
