- name: Allow {{ ansible_user_id }} to run sudo without password
  become: true
  lineinfile:
    dest: /etc/sudoers
    line: '{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  tags:
    - sudo
    - sudo-no-password
