# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# Tools
brew "git"
brew "node"

# Superior editor
brew "neovim", args: ['HEAD']

# Shell
brew "zsh"
brew "libxdg-basedir"
brew "pfetch"

# Utilities
brew "fd"
brew "fzf"
brew "ripgrep"
brew "exa"
brew "tealdeer"
brew "trash-cli"

# GUI apps
cask "rectangle"

# Fonts
cask "font-jetbrains-mono-nerd-font"
