- link:
    ~/.config/kdeglobals: kde-plasma/kdeglobals
    ~/.config/khotkeysrc: kde-plasma/khotkeysrc
    ~/.config/krunnerrc: kde-plasma/krunnerrc
    ~/.config/kwinrc: kde-plasma/kwinrc
    ~/.config/kwinrulesrc: kde-plasma/kwinrulesrc
    ~/.config/plasmashellrc: kde-plasma/plasmashellrc
    ~/.config/kglobalshortcutsrc: kde-plasma/kglobalshortcutsrc
    ~/.config/plasma-org.kde.plasma.desktop-appletsrc: kde-plasma/plasma-org.kde.plasma.desktop-appletsrc
    ~/.config/touchpadxlibinputrc: kde-plasma/touchpadxlibinputrc

