#!/bin/env bash

CODESDIR=${CODESDIR:-$HOME/Codes}

[[ ! -d $CODESDIR ]] && "Codes directory not found" && exit
pushd $CODESDIR > /dev/null

if [ `command -v fd` ]; then
  CMD="fd . --type d --hidden --follow --exclude .git"
else
  CMD="find . -type d -not -path './node_modules*' -not -path '*.git*'"
fi

if [ -n "$TMUX" ]; then
  CHOSEN=`$CMD | fzf-tmux -p`
else 
  CHOSEN=`$CMD | fzf`
fi

RET=$?

popd > /dev/null

if [ $RET = 0 ]; then
  # pushd "$CODESDIR/$CHOSEN"
  echo "$CODESDIR/$CHOSEN"
fi

