#! /bin/bash

[ ! -t 0 ] && notify-send "Run in terminal !" && exit
# get current workspace name
# ws=`i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2`

# marking current terminal window (to be jumped to)
i3-msg --quiet mark spawning_term

qutebrowser --target window http://localhost:3000 2>/dev/null &
disown

kitty --detach --title Server sh -c "cd ~/Codes/IEO-2022 && npm run dev; exec zsh" &
disown

i3-msg --quiet layout tabbed

# QUTE_PID=$!

launch () {
 i3-msg '[workspace="__focused__" class="qutebrowser"] focus' 2>/dev/null | jq '.[].success'
}

launched=`launch`
while [ $launched != "true" ]; do
 launched=`launch`
done

i3-msg --quiet '[workspace="__focused__" class="qutebrowser"]' move container right
i3-msg --quiet '[workspace="__focused__" class="qutebrowser"]' resize set width 446
i3-msg --quiet '[con_mark="spawning_term"]' move right
i3-msg --quiet '[con_mark="spawning_term"]' focus
i3-msg --quiet unmark spawning_term


cd ~/Codes/IEO-2022 && lvim
