#!/usr/bin/env bash
set -e

# shellcheck disable=2046,2086
SCRIPT_DIR="$(realpath $(dirname ${BASH_SOURCE[0]}))"
source "${SCRIPT_DIR}/install.env"

printLineBanner() {
	printf '\e[1;34m%0.s#\e[0m' $(seq 1 $(stty size | awk '{print $2}'))
}

cd "${BASE_DIR}"
git submodule update --init --recursive

sudoSuffix="-sudo"
exitIfConfigNotFound=false    # used as a flag to exit IF a config file is NOT found
for config in "${@}"; do
    config=${config%"$sudoSuffix"}
    configFilepath="${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
    if [[ ! -e $configFilepath ]]; then
      echo -e "Dotbot config \\033[1;31m$configFilepath \\033[0mDOESN'T exists"

      exitIfConfigNotFound=true
    fi
done

# exit if a config filepath is NOT found
if [[ $exitIfConfigNotFound == true ]]; then
    echo -e "\nexiting"
    exit 1
fi

# cleanup variables
unset sudoSuffix
unset exitIfConfigNotFound
