#!/bin/env bash

PLAYLIST=${1:-"https://youtube.com/playlist?list=PLqeSJS3N5tzhPp3SkqKJm9rdCZu69Z1_7"}

notify-send "Playing Lofi.."

mpv \
  --x11-name=lofi \
  --shuffle \
  --force-window \
  --script-opts=osc-visibility=always \
  --ytdl-format="[height <=? 480][vbr < 800]" \
  "$PLAYLIST"
