#!/bin/bash

exec /usr/bin/google-chrome-stable --force-dark-mode --app='chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/index.html' & exit
# nohup /usr/bin/google-chrome-stable --app='chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/index.html' > /dev/null
# disown

