#!/bin/env bash

VOL=`amixer get Master | grep -Po '[0-9]+(?=%)' | head -1`


if [[ $1 = "mute" ]]; then
  if amixer get Master | grep -q "\[off\]"; then
    echo "$VOL!" >> /tmp/xob-volume-fifo
  else
    echo "$VOL" >> /tmp/xob-volume-fifo
  fi
else
  echo "$VOL" >> /tmp/xob-volume-fifo
fi

